version: 2

builds:
  - binary: Sushupti
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "Sushupti_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
